### ISSUE TITLE
save states of screens

### ISSUE THREAD

**Issue by jligeza** [kivy-garden/garden.router#1]
How can I save states of screens under management of the router? When a user writes something in a text input, and switches screen, text is lost. I tried to save screen objects in a dict, and return them from there, but is raises an exception:

_kivy.uix.screenmanager.ScreenManagerException: Screen already managed by this ScreenManager (are you calling `switch_to` when you should be setting `current`?)_

In routers code, changing `sm.switch_to(screen)` → `sm.current = name` doesn't work.

**Comment by sdementen** [comment]
In the routing function, you can return a screen that already exists (vs return a new instance each time).

For instance:

```
class MainRouter(Router):
    def __init__(self):
        self._index = MainScreen()
        self._about = AboutScreen()
        super(MainRouter, self).__init__()

    @route("/")
    def index(self):
        return self._index

    @route("/hello")
    def about(self):
        return self._about
```

**Comment by jligeza** [comment]
I was saving screens in a global dict instead of inside MainRouter instance. I have no idea why that didn't work, thanks.
